<a href="https://colab.research.google.com/github/SelinOlcay/ImageProcessing/blob/main/Week-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [6]:
array =np.zeros( (3,3) )
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
array =np.ones( (2,5) )
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
n = int(input("Kac Adet Sayi Girilecek: "))
a = []
for i in range(0,n):
    elem = int(input("Sayiyi Girin: "))
    a.append(elem)
avg = sum(a) / n
print("Girilen Sayilarin Ortalamasi: ", round(avg,2))

Kac Adet Sayi Girilecek: 5
Sayiyi Girin: 4
Sayiyi Girin: 5
Sayiyi Girin: 6
Sayiyi Girin: 3
Sayiyi Girin: 4
Girilen Sayilarin Ortalamasi:  4.4
